FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# PMS API

Interface to consume data from the Property Management System

# Group Property resources

## Property resources represent each holiday cottage available to let [/property]

The property endpoint can be used for all searches - either availability searches or feature searches. Filtering can be done by
passing in key/value pairs as parameters in the URL. If no filters are passed all currently *approved* properties will be returned. 

### List/Search all properties [GET]

+ Response 200 (application/json)


        {
            "searchId": 1234,
            "paginator": {
                "totalResults": 1,
                "page": 1,
                "pageSize": 10
            },
            "orderBy": null,
            "filter": null,
            "results": [
                {
                    "id": "10006",
                    "reference": "pintail-cottage",
                    "url": "http://private-5bb1f-pmsapi1.apiary-mock.com/property/pintail-cottage",
                    "slug": "pintail-cottage",
                    "name": "Pintail Cottage",
                    "status": "approved",
                    "address": {
                                "house_no": "5",
                                "street": "Pintail Avenue",
                                "town": "Saltings Reach",
                                "city": "Lelant",
                                "county": "Cornwall",
                                "postcode": "TR27 6GN"
                            },
                    "coordinates": {
                        "latitude": 52.2345,
                        "longitude": 1.2345
                    },
                    "location": {
                        "id": "38",
                        "name": "Lelant & Saltings Reach",
                        "slug": "lelant-saltings"
                    },
                    "sleeps": 6,
                    "bedrooms": {
                        "total": 3,
                        "superking": 0,
                        "king": 0,
                        "double": 1,
                        "twin": 2,
                        "zipnlock": 0,
                        "other": 0,
                        "information": ""
                    },
                    "bathrooms": {
                        "en-suite":1,
                        "standard":1,
                        "wc":1,
                        "other":0
                    },
                    "gemsRating": 4,
                    "goLiveDate": "2016-05-09",
                    "features": {
                        "pets": true,
                        "children": true,
                        "disabled": false,
                        "parking": true,
                        "wifi": true,
                        "crib": false,
                        "seaviews": false,
                        "closetobeach": true,
                        "woodburner": true,
                        "washingmachine": true,
                        "tumbledryer": false,
                        "pool": false,
                        "cot": true
                    }
                    "managed": true,
                    "minibreaks": true,
                    "boutique": true,
                    "changeOverDay": "Friday",
                    "checkInTime": "4:30pm",
                    "checkOutTime": "10:00am",
                    "images": [
                        {
                            "filename": "001.jpg",
                            "alt": "Pintail Cottage",
                            "width": 1280,
                            "height": 960,
                            "url": "https://assets.cornishgems.com/properties/pintail-cottage/001.jpg"
                        }
                    ],
                    "specialOffers": [
                         {
                            "discountCode": "X10250517X",
                            "fromDate": "2017-05-25",
                            "toDate": "2017-06-01",
                            "description": "10% Discount for week commencing 25th May 2017",
                            "type": "%",
                            "amount": 10
                         }
                    ],
                    "calendar": "http://pmsapi1.apiary.io/property/pintail-cottage/calendar",
                    "booking": "http://pmsapi1.apiary.io/booking"
                }
            ]
        }


## Retrieve a property resource [/property/{reference}]

+ Parameters
    + reference (string) - reference for the property resource in the form of a string

### Property [GET]

+ Response 200 (application/json)

        {
            "id": "10006",
            "reference": "pintail-cottage",
            "url": "http://private-5bb1f-pmsapi1.apiary-mock.com/property/pintail-cottage",
            "slug": "pintail-cottage",
            "name": "Pintail Cottage",
            "status": "approved",
            "address": {
                        "house_no": "5",
                        "street": "Pintail Avenue",
                        "town": "Saltings Reach",
                        "city": "Lelant",
                        "county": "Cornwall",
                        "postcode": "TR27 6GN"
                    },
            "coordinates": {
                "latitude": 52.2345,
                "longitude": 1.2345
            },
            "location": {
                "id": "38",
                "name": "Lelant & Saltings Reach",
                "slug": "lelant-saltings"
            },
            "sleeps": 6,
            "bedrooms": {
                "total": 3,
                "superking": 0,
                "king": 0,
                "double": 1,
                "twin": 2,
                "zipnlock": 0,
                "other": 0,
                "information": ""
            },
            "bathrooms": {
                "en-suite":1,
                "standard":1,
                "wc":1,
                "other":0
            },
            "gemsRating": 4,
            "goLiveDate": "2016-05-09",
            "features": {
                "pets": true,
                "children": true,
                "disabled": false,
                "parking": true,
                "wifi": true,
                "crib": false,
                "seaviews": false,
                "closetobeach": true,
                "woodburner": true,
                "washingmachine": true,
                "tumbledryer": false,
                "pool": false,
                "cot": true
            }
            "managed": true,
            "minibreaks": true,
            "boutique": true,
            "changeOverDay": "Friday",
            "checkInTime": "4:30pm",
            "checkOutTime": "10:00am",
            "images": [
                {
                    "filename": "001.jpg",
                    "alt": "Pintail Cottage",
                    "width": 640,
                    "height": 480,
                    "url": "https://assets.cornishgems.com/properties/pintail-cottage/001.jpg"
                }
            ],
            "specialOffers": [
                 {
                    "discountCode": "X10250517X",
                    "fromDate": "2017-05-25",
                    "toDate": "2017-06-01",
                    "description": "10% Discount for week commencing 25th May 2017",
                    "type": "%",
                    "amount": 10
                 }
            ],
            "calendar": "http://pmsapi1.apiary.io/property/pintail-cottage/calendar",
            "booking": "http://pmsapi1.apiary.io/booking"
        }


## Retrieve availability data for a Property [/property/{reference}/availability]
The availability calendar for a property returns an array of date objects from the the first of the current month to
the end of current availability. Please review the wiki for details on availability object.

+ Parameters
    + reference (string) - reference for the property resource in the form of a string

### Availability [GET]

+ Response 200 (application/json)

        [
        "2017-05-01":{
          "peak":0,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"O"
        },
        "2017-05-02":{
          "peak":0,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"O"
        },
        "2017-05-03":{
          "peak":0,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"O"
        },
        "2017-05-04":{
          "peak":0,
          "status":"C",
          "daysToNextBooking":8,
          "bookingType":"O"
        },
        "2017-05-05":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":7,
          "bookingType":"",
          "changeOverDay":true
        },
        "2017-05-06":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":6,
          "bookingType":""
        },
        "2017-05-07":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":5,
          "bookingType":""
        },
        "2017-05-08":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":4,
          "bookingType":""
        },
        "2017-05-09":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":3,
          "bookingType":""
        },
        "2017-05-10":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":2,
          "bookingType":""
        },
        "2017-05-11":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":1,
          "bookingType":""
        },
        "2017-05-12":{
          "peak":1,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"S",
          "changeOverDay":true
        },
        "2017-05-13":{
          "peak":1,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"S"
        },
        "2017-05-14":{
          "peak":1,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"S"
        },
        "2017-05-15":{
          "peak":1,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"S"
        },
        "2017-05-16":{
          "peak":1,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"S"
        },
        "2017-05-17":{
          "peak":1,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"S"
        },
        "2017-05-18":{
          "peak":1,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"S"
        },
        "2017-05-19":{
          "peak":1,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"S",
          "changeOverDay":true
        },
        "2017-05-20":{
          "peak":1,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"S"
        },
        "2017-05-21":{
          "peak":1,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"S"
        },
        "2017-05-22":{
          "peak":0,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"S"
        },
        "2017-05-23":{
          "peak":0,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"S"
        },
        "2017-05-24":{
          "peak":0,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"S"
        },
        "2017-05-25":{
          "peak":0,
          "status":"C",
          "daysToNextBooking":8,
          "bookingType":"S"
        },
        "2017-05-26":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":7,
          "bookingType":"",
          "changeOverDay":true
        },
        "2017-05-27":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":6,
          "bookingType":""
        },
        "2017-05-28":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":5,
          "bookingType":""
        },
        "2017-05-29":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":4,
          "bookingType":""
        },
        "2017-05-30":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":3,
          "bookingType":""
        },
        "2017-05-31":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":2,
          "bookingType":""
        },
        "2017-06-01":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":1,
          "bookingType":""
        },
        "2017-06-02":{
          "peak":0,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"S",
          "changeOverDay":true
        },
        "2017-06-03":{
          "peak":1,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"S"
        },
        "2017-06-04":{
          "peak":1,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"S"
        },
        "2017-06-05":{
          "peak":1,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"S"
        },
        "2017-06-06":{
          "peak":1,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"S"
        },
        "2017-06-07":{
          "peak":1,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"S"
        },
        "2017-06-08":{
          "peak":1,
          "status":"C",
          "daysToNextBooking":8,
          "bookingType":"S"
        },
        "2017-06-09":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":7,
          "bookingType":"",
          "changeOverDay":true
        },
        "2017-06-10":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":6,
          "bookingType":""
        },
        "2017-06-11":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":5,
          "bookingType":""
        },
        "2017-06-12":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":4,
          "bookingType":""
        },
        "2017-06-13":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":3,
          "bookingType":""
        },
        "2017-06-14":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":2,
          "bookingType":""
        },
        "2017-06-15":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":1,
          "bookingType":""
        },
        "2017-06-16":{
          "peak":1,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"S",
          "changeOverDay":true
        },
        "2017-06-17":{
          "peak":1,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"S"
        },
        "2017-06-18":{
          "peak":1,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"S"
        },
        "2017-06-19":{
          "peak":1,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"S"
        },
        "2017-06-20":{
          "peak":1,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"S"
        },
        "2017-06-21":{
          "peak":1,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"S"
        },
        "2017-06-22":{
          "peak":1,
          "status":"C",
          "daysToNextBooking":8,
          "bookingType":"S"
        },
        "2017-06-23":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":7,
          "bookingType":"",
          "changeOverDay":true
        },
        "2017-06-24":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":6,
          "bookingType":""
        },
        "2017-06-25":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":5,
          "bookingType":""
        },
        "2017-06-26":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":4,
          "bookingType":""
        },
        "2017-06-27":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":3,
          "bookingType":""
        },
        "2017-06-28":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":2,
          "bookingType":""
        },
        "2017-06-29":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":1,
          "bookingType":""
        },
        "2017-06-30":{
          "peak":1,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"S",
          "changeOverDay":true
        },
        "2017-07-01":{
          "peak":1,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"S"
        },
        "2017-07-02":{
          "peak":1,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"S"
        },
        "2017-07-03":{
          "peak":1,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"S"
        },
        "2017-07-04":{
          "peak":1,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"S"
        },
        "2017-07-05":{
          "peak":1,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"S"
        },
        "2017-07-06":{
          "peak":1,
          "status":"C",
          "daysToNextBooking":22,
          "bookingType":"S"
        },
        "2017-07-07":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":21,
          "bookingType":"",
          "changeOverDay":true
        },
        "2017-07-08":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":20,
          "bookingType":""
        },
        "2017-07-09":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":19,
          "bookingType":""
        },
        "2017-07-10":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":18,
          "bookingType":""
        },
        "2017-07-11":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":17,
          "bookingType":""
        },
        "2017-07-12":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":16,
          "bookingType":""
        },
        "2017-07-13":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":15,
          "bookingType":""
        },
        "2017-07-14":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":14,
          "bookingType":"",
          "changeOverDay":true
        },
        "2017-07-15":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":13,
          "bookingType":""
        },
        "2017-07-16":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":12,
          "bookingType":""
        },
        "2017-07-17":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":11,
          "bookingType":""
        },
        "2017-07-18":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":10,
          "bookingType":""
        },
        "2017-07-19":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":9,
          "bookingType":""
        },
        "2017-07-20":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":8,
          "bookingType":""
        },
        "2017-07-21":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":7,
          "bookingType":"",
          "changeOverDay":true
        },
        "2017-07-22":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":6,
          "bookingType":""
        },
        "2017-07-23":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":5,
          "bookingType":""
        },
        "2017-07-24":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":4,
          "bookingType":""
        },
        "2017-07-25":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":3,
          "bookingType":""
        },
        "2017-07-26":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":2,
          "bookingType":""
        },
        "2017-07-27":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":1,
          "bookingType":""
        },
        "2017-07-28":{
          "peak":1,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"S",
          "changeOverDay":true
        },
        "2017-07-29":{
          "peak":1,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"S"
        },
        "2017-07-30":{
          "peak":1,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"S"
        },
        "2017-07-31":{
          "peak":1,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"S"
        },
        "2017-08-01":{
          "peak":1,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"S"
        },
        "2017-08-02":{
          "peak":1,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"S"
        },
        "2017-08-03":{
          "peak":1,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"S"
        },
        "2017-08-04":{
          "peak":1,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"S",
          "changeOverDay":true
        },
        "2017-08-05":{
          "peak":1,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"S"
        },
        "2017-08-06":{
          "peak":1,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"S"
        },
        "2017-08-07":{
          "peak":1,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"S"
        },
        "2017-08-08":{
          "peak":1,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"S"
        },
        "2017-08-09":{
          "peak":1,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"S"
        },
        "2017-08-10":{
          "peak":1,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"S"
        },
        "2017-08-11":{
          "peak":1,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"O",
          "changeOverDay":true
        },
        "2017-08-12":{
          "peak":1,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"O"
        },
        "2017-08-13":{
          "peak":1,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"O"
        },
        "2017-08-14":{
          "peak":1,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"O"
        },
        "2017-08-15":{
          "peak":1,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"O"
        },
        "2017-08-16":{
          "peak":1,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"O"
        },
        "2017-08-17":{
          "peak":1,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"O"
        },
        "2017-08-18":{
          "peak":1,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"S",
          "changeOverDay":true
        },
        "2017-08-19":{
          "peak":1,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"S"
        },
        "2017-08-20":{
          "peak":1,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"S"
        },
        "2017-08-21":{
          "peak":1,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"S"
        },
        "2017-08-22":{
          "peak":1,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"S"
        },
        "2017-08-23":{
          "peak":1,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"S"
        },
        "2017-08-24":{
          "peak":1,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"S"
        },
        "2017-08-25":{
          "peak":1,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"S",
          "changeOverDay":true
        },
        "2017-08-26":{
          "peak":1,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"S"
        },
        "2017-08-27":{
          "peak":1,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"S"
        },
        "2017-08-28":{
          "peak":1,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"S"
        },
        "2017-08-29":{
          "peak":1,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"S"
        },
        "2017-08-30":{
          "peak":1,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"S"
        },
        "2017-08-31":{
          "peak":1,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"S"
        },
        "2017-09-01":{
          "peak":1,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"S",
          "changeOverDay":true
        },
        "2017-09-02":{
          "peak":1,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"S"
        },
        "2017-09-03":{
          "peak":1,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"S"
        },
        "2017-09-04":{
          "peak":1,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"S"
        },
        "2017-09-05":{
          "peak":1,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"S"
        },
        "2017-09-06":{
          "peak":1,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"S"
        },
        "2017-09-07":{
          "peak":1,
          "status":"C",
          "daysToNextBooking":29,
          "bookingType":"S"
        },
        "2017-09-08":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":28,
          "bookingType":"",
          "changeOverDay":true
        },
        "2017-09-09":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":27,
          "bookingType":""
        },
        "2017-09-10":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":26,
          "bookingType":""
        },
        "2017-09-11":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":25,
          "bookingType":""
        },
        "2017-09-12":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":24,
          "bookingType":""
        },
        "2017-09-13":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":23,
          "bookingType":""
        },
        "2017-09-14":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":22,
          "bookingType":""
        },
        "2017-09-15":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":21,
          "bookingType":"",
          "changeOverDay":true
        },
        "2017-09-16":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":20,
          "bookingType":""
        },
        "2017-09-17":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":19,
          "bookingType":""
        },
        "2017-09-18":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":18,
          "bookingType":""
        },
        "2017-09-19":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":17,
          "bookingType":""
        },
        "2017-09-20":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":16,
          "bookingType":""
        },
        "2017-09-21":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":15,
          "bookingType":""
        },
        "2017-09-22":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":14,
          "bookingType":"",
          "changeOverDay":true
        },
        "2017-09-23":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":13,
          "bookingType":""
        },
        "2017-09-24":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":12,
          "bookingType":""
        },
        "2017-09-25":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":11,
          "bookingType":""
        },
        "2017-09-26":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":10,
          "bookingType":""
        },
        "2017-09-27":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":9,
          "bookingType":""
        },
        "2017-09-28":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":8,
          "bookingType":""
        },
        "2017-09-29":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":7,
          "bookingType":"",
          "changeOverDay":true
        },
        "2017-09-30":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":6,
          "bookingType":""
        },
        "2017-10-01":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":5,
          "bookingType":""
        },
        "2017-10-02":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":4,
          "bookingType":""
        },
        "2017-10-03":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":3,
          "bookingType":""
        },
        "2017-10-04":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":2,
          "bookingType":""
        },
        "2017-10-05":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":1,
          "bookingType":""
        },
        "2017-10-06":{
          "peak":0,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"S",
          "changeOverDay":true
        },
        "2017-10-07":{
          "peak":0,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"S"
        },
        "2017-10-08":{
          "peak":1,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"S"
        },
        "2017-10-09":{
          "peak":0,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"S"
        },
        "2017-10-10":{
          "peak":0,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"S"
        },
        "2017-10-11":{
          "peak":0,
          "status":"C",
          "daysToNextBooking":0,
          "bookingType":"S"
        },
        "2017-10-12":{
          "peak":0,
          "status":"C",
          "daysToNextBooking":456,
          "bookingType":"S"
        },
        "2017-10-13":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":455,
          "bookingType":"",
          "changeOverDay":true
        },
        "2017-10-14":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":454,
          "bookingType":""
        },
        "2017-10-15":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":453,
          "bookingType":""
        },
        "2017-10-16":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":452,
          "bookingType":""
        },
        "2017-10-17":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":451,
          "bookingType":""
        },
        "2017-10-18":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":450,
          "bookingType":""
        },
        "2017-10-19":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":449,
          "bookingType":""
        },
        "2017-10-20":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":448,
          "bookingType":"",
          "changeOverDay":true
        },
        "2017-10-21":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":447,
          "bookingType":""
        },
        "2017-10-22":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":446,
          "bookingType":""
        },
        "2017-10-23":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":445,
          "bookingType":""
        },
        "2017-10-24":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":444,
          "bookingType":""
        },
        "2017-10-25":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":443,
          "bookingType":""
        },
        "2017-10-26":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":442,
          "bookingType":""
        },
        "2017-10-27":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":441,
          "bookingType":"",
          "changeOverDay":true
        },
        "2017-10-28":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":440,
          "bookingType":""
        },
        "2017-10-29":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":439,
          "bookingType":""
        },
        "2017-10-30":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":438,
          "bookingType":""
        },
        "2017-10-31":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":437,
          "bookingType":""
        },
        "2017-11-01":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":436,
          "bookingType":""
        },
        "2017-11-02":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":435,
          "bookingType":""
        },
        "2017-11-03":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":434,
          "bookingType":"",
          "changeOverDay":true
        },
        "2017-11-04":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":433,
          "bookingType":""
        },
        "2017-11-05":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":432,
          "bookingType":""
        },
        "2017-11-06":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":431,
          "bookingType":""
        },
        "2017-11-07":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":430,
          "bookingType":""
        },
        "2017-11-08":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":429,
          "bookingType":""
        },
        "2017-11-09":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":428,
          "bookingType":""
        },
        "2017-11-10":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":427,
          "bookingType":"",
          "changeOverDay":true
        },
        "2017-11-11":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":426,
          "bookingType":""
        },
        "2017-11-12":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":425,
          "bookingType":""
        },
        "2017-11-13":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":424,
          "bookingType":""
        },
        "2017-11-14":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":423,
          "bookingType":""
        },
        "2017-11-15":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":422,
          "bookingType":""
        },
        "2017-11-16":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":421,
          "bookingType":""
        },
        "2017-11-17":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":420,
          "bookingType":"",
          "changeOverDay":true
        },
        "2017-11-18":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":419,
          "bookingType":""
        },
        "2017-11-19":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":418,
          "bookingType":""
        },
        "2017-11-20":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":417,
          "bookingType":""
        },
        "2017-11-21":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":416,
          "bookingType":""
        },
        "2017-11-22":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":415,
          "bookingType":""
        },
        "2017-11-23":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":414,
          "bookingType":""
        },
        "2017-11-24":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":413,
          "bookingType":"",
          "changeOverDay":true
        },
        "2017-11-25":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":412,
          "bookingType":""
        },
        "2017-11-26":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":411,
          "bookingType":""
        },
        "2017-11-27":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":410,
          "bookingType":""
        },
        "2017-11-28":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":409,
          "bookingType":""
        },
        "2017-11-29":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":408,
          "bookingType":""
        },
        "2017-11-30":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":407,
          "bookingType":""
        },
        "2017-12-01":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":406,
          "bookingType":"",
          "changeOverDay":true
        },
        "2017-12-02":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":405,
          "bookingType":""
        },
        "2017-12-03":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":404,
          "bookingType":""
        },
        "2017-12-04":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":403,
          "bookingType":""
        },
        "2017-12-05":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":402,
          "bookingType":""
        },
        "2017-12-06":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":401,
          "bookingType":""
        },
        "2017-12-07":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":400,
          "bookingType":""
        },
        "2017-12-08":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":399,
          "bookingType":"",
          "changeOverDay":true
        },
        "2017-12-09":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":398,
          "bookingType":""
        },
        "2017-12-10":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":397,
          "bookingType":""
        },
        "2017-12-11":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":396,
          "bookingType":""
        },
        "2017-12-12":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":395,
          "bookingType":""
        },
        "2017-12-13":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":394,
          "bookingType":""
        },
        "2017-12-14":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":393,
          "bookingType":""
        },
        "2017-12-15":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":392,
          "bookingType":"",
          "changeOverDay":true
        },
        "2017-12-16":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":391,
          "bookingType":""
        },
        "2017-12-17":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":390,
          "bookingType":""
        },
        "2017-12-18":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":389,
          "bookingType":""
        },
        "2017-12-19":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":388,
          "bookingType":""
        },
        "2017-12-20":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":387,
          "bookingType":""
        },
        "2017-12-21":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":386,
          "bookingType":""
        },
        "2017-12-22":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":385,
          "bookingType":"",
          "changeOverDay":true
        },
        "2017-12-23":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":384,
          "bookingType":""
        },
        "2017-12-24":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":383,
          "bookingType":""
        },
        "2017-12-25":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":382,
          "bookingType":""
        },
        "2017-12-26":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":381,
          "bookingType":""
        },
        "2017-12-27":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":380,
          "bookingType":""
        },
        "2017-12-28":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":379,
          "bookingType":""
        },
        "2017-12-29":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":378,
          "bookingType":"",
          "changeOverDay":true
        },
        "2017-12-30":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":377,
          "bookingType":""
        },
        "2017-12-31":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":376,
          "bookingType":""
        },
        "2018-01-01":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":375,
          "bookingType":""
        },
        "2018-01-02":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":374,
          "bookingType":""
        },
        "2018-01-03":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":373,
          "bookingType":""
        },
        "2018-01-04":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":372,
          "bookingType":""
        },
        "2018-01-05":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":371,
          "bookingType":"",
          "changeOverDay":true
        },
        "2018-01-06":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":370,
          "bookingType":""
        },
        "2018-01-07":{
          "peak":1,
          "status":"A",
          "daysToNextBooking":369,
          "bookingType":""
        },
        "2018-01-08":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":368,
          "bookingType":""
        },
        "2018-01-09":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":367,
          "bookingType":""
        },
        "2018-01-10":{
          "peak":0,
          "status":"A",
          "daysToNextBooking":366,
          "bookingType":""
        }
   
        ]
        
## Retrieve customer feedback for a Property [/property/{reference}/feedback]
Endpoint for property feedback that has been set for public consumption.

+ Parameters
    + reference (string) - reference ID of the property resource in the form of a string

### Feedback [GET]

+ Response 200 (application/json)


        [
            {
                "date": "2015-09-21",
                "name": "M Smith",
                "guestId": 1234,
                "bookingId": 5643,
                "comment": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
            },
            {
                "date": "2015-08-20",
                "name": "J Blogs",
                "guestId": 1325,
                "bookingId": 5612,
                "comment": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
            },
            {
                "date": "2015-07-20",
                "name": "ABC",
                "guestId": 1621,
                "bookingId": 4526,
                "comment": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
            },            
        ]

## Retrieve bookings associated with a Property [/property/{reference}/booking]

+ Parameters
    + reference (string) - reference ID of the property resource in the form of a string

### Booking [GET]

+ Response 200 (application/json)


        [
            {
                "bookingId": 30312,
                "propertyId": 10006,
                "guestId": 31600,
                "added": "2017-04-01",
                "confirmed": "2017-04-01",
                "checkin": "2017-05-20",
                "checkout": "2017-05-27",
                "checkinTime": "4:30pm",
                "status": "C",
                "type": "M",
                "contactInformation": {
                    "primary": "07778787878",
                    "secondary": "01234123123",
                },
                "partyDetails": {
                    "adults": 2,
                    "children": 2,
                    "infants": 0,
                    "dogs": 1
                },
                "tariff": {
                    "total": 615.40,
                    "deposit": 0,
                    "balance": 615.40
                }
                "extras": [
                    {
                        "extraId": "Pet01",
                        "description": "Pet Supplement (Cornish Gem)",
                        "comments": "1 x Pet Supplement (Cornish Gem)",
                        "net": 24.17,
                        "vat": 4.83,
                        "gross": 29.00
                    }
                ],
                "receipts": [
                    {
                        "receiptId": 55543,
                        "date": "2017-04-01",
                        "description": "Extras Paid",
                        "method": "WPDC",
                        "amount": 29.00
                    }, {
                        "receiptId": 55544,
                        "date": "2017-04-01",
                        "description": "Balance Paid",
                        "method": "WPDC",
                        "amount": 615.40
                    }
                ]
            },
            {
                "bookingId": 29634,
                "guestId": 28171,
                "added": "2017-04-02",
                "confirmed": "2017-04-03",
                "checkin": "2017-06-10",
                "checkout": "2017-06-17",
                "checkinTime": "4:30pm",
                "status": "C",
                "type": "W",
                "contactInformation": {
                    "primary": "07778787878",
                    "secondary": "01234123123",
                },
                "partyDetails": {
                    "adults": 2,
                    "children": 0,
                    "infants": 1,
                    "dogs": 0
                },
                "tariff": {
                    "total": 939.00,
                    "deposit": 313.00,
                    "balance": 626.00
                }
                "extras": null,
                "receipts": [
                    {
                        "receiptId": 55585,
                        "date": "2017-04-02",
                        "description": "Deposit Paid",
                        "method": "WPDC",
                        "amount": 313.00
                    }
                ]
            }
        ]

## Retrieve weekly tariffs for a year for a Property [/property/{reference}/tariff/{year}]

This will provide the week on week standard tariff for the property. If minibreaks are available it will
also return the minibreak tariff that can be applied IF a minibreak is available on any particular day.

+ Parameters
    + reference (string) - reference ID of the property resource in the form of a string
    + year (number) - the year in the form of an integer

### Tariff [GET]

+ Response 200 (application/json)

        [
           {
              "checkin":"2017-01-06",
              "tariff":"519.00",
              "minibreakTariffs":{
                 "threeNight":415.2,
                 "fourNight":441.15,
                 "fiveNight":467.1
              }
           },
           {
              "checkin":"2017-01-13",
              "tariff":"519.00",
              "minibreakTariffs":{
                 "threeNight":415.2,
                 "fourNight":441.15,
                 "fiveNight":467.1
              }
           },
           {
              "checkin":"2017-01-20",
              "tariff":"519.00",
              "minibreakTariffs":{
                 "threeNight":415.2,
                 "fourNight":441.15,
                 "fiveNight":467.1
              }
           },
           {
              "checkin":"2017-01-27",
              "tariff":"519.00",
              "minibreakTariffs":{
                 "threeNight":415.2,
                 "fourNight":441.15,
                 "fiveNight":467.1
              }
           },
           {
              "checkin":"2017-02-03",
              "tariff":"519.00",
              "minibreakTariffs":{
                 "threeNight":415.2,
                 "fourNight":441.15,
                 "fiveNight":467.1
              }
           },
           {
              "checkin":"2017-02-10",
              "tariff":"669.00",
              "minibreakTariffs":{
                 "threeNight":535.2,
                 "fourNight":568.65,
                 "fiveNight":602.1
              }
           },
           {
              "checkin":"2017-02-17",
              "tariff":"519.00",
              "minibreakTariffs":{
                 "threeNight":415.2,
                 "fourNight":441.15,
                 "fiveNight":467.1
              }
           },
           {
              "checkin":"2017-02-24",
              "tariff":"595.00",
              "minibreakTariffs":{
                 "threeNight":476,
                 "fourNight":505.75,
                 "fiveNight":535.5
              }
           },
           {
              "checkin":"2017-03-03",
              "tariff":"595.00",
              "minibreakTariffs":{
                 "threeNight":476,
                 "fourNight":505.75,
                 "fiveNight":535.5
              }
           },
           {
              "checkin":"2017-03-10",
              "tariff":"595.00",
              "minibreakTariffs":{
                 "threeNight":476,
                 "fourNight":505.75,
                 "fiveNight":535.5
              }
           },
           {
              "checkin":"2017-03-17",
              "tariff":"669.00",
              "minibreakTariffs":{
                 "threeNight":535.2,
                 "fourNight":568.65,
                 "fiveNight":602.1
              }
           },
           {
              "checkin":"2017-03-24",
              "tariff":"669.00",
              "minibreakTariffs":{
                 "threeNight":535.2,
                 "fourNight":568.65,
                 "fiveNight":602.1
              }
           },
           {
              "checkin":"2017-03-31",
              "tariff":"895.00",
              "minibreakTariffs":{
                 "threeNight":716,
                 "fourNight":760.75,
                 "fiveNight":805.5
              }
           },
           {
              "checkin":"2017-04-07",
              "tariff":"895.00",
              "minibreakTariffs":{
                 "threeNight":716,
                 "fourNight":760.75,
                 "fiveNight":805.5
              }
           },
           {
              "checkin":"2017-04-14",
              "tariff":"895.00",
              "minibreakTariffs":{
                 "threeNight":716,
                 "fourNight":760.75,
                 "fiveNight":805.5
              }
           },
           {
              "checkin":"2017-04-21",
              "tariff":"745.00",
              "minibreakTariffs":{
                 "threeNight":596,
                 "fourNight":633.25,
                 "fiveNight":670.5
              }
           },
           {
              "checkin":"2017-04-28",
              "tariff":"745.00",
              "minibreakTariffs":{
                 "threeNight":596,
                 "fourNight":633.25,
                 "fiveNight":670.5
              }
           },
           {
              "checkin":"2017-05-05",
              "tariff":"745.00",
              "minibreakTariffs":{
                 "threeNight":596,
                 "fourNight":633.25,
                 "fiveNight":670.5
              }
           },
           {
              "checkin":"2017-05-12",
              "tariff":"745.00",
              "minibreakTariffs":{
                 "threeNight":596,
                 "fourNight":633.25,
                 "fiveNight":670.5
              }
           },
           {
              "checkin":"2017-05-19",
              "tariff":"745.00",
              "minibreakTariffs":{
                 "threeNight":596,
                 "fourNight":633.25,
                 "fiveNight":670.5
              }
           },
           {
              "checkin":"2017-05-26",
              "tariff":"951.20",
              "minibreakTariffs":{
                 "threeNight":760.96,
                 "fourNight":808.52,
                 "fiveNight":856.08
              }
           },
           {
              "checkin":"2017-06-02",
              "tariff":"925.00",
              "minibreakTariffs":{
                 "threeNight":740,
                 "fourNight":786.25,
                 "fiveNight":832.5
              }
           },
           {
              "checkin":"2017-06-09",
              "tariff":"925.00",
              "minibreakTariffs":{
                 "threeNight":740,
                 "fourNight":786.25,
                 "fiveNight":832.5
              }
           },
           {
              "checkin":"2017-06-16",
              "tariff":"925.00",
              "minibreakTariffs":{
                 "threeNight":740,
                 "fourNight":786.25,
                 "fiveNight":832.5
              }
           },
           {
              "checkin":"2017-06-23",
              "tariff":"925.00",
              "minibreakTariffs":{
                 "threeNight":740,
                 "fourNight":786.25,
                 "fiveNight":832.5
              }
           },
           {
              "checkin":"2017-06-30",
              "tariff":"1039.00",
              "minibreakTariffs":{
                 "threeNight":831.2,
                 "fourNight":883.15,
                 "fiveNight":935.1
              }
           },
           {
              "checkin":"2017-07-07",
              "tariff":"1339.00",
              "minibreakTariffs":{
                 "threeNight":1071.2,
                 "fourNight":1138.15,
                 "fiveNight":1205.1
              }
           },
           {
              "checkin":"2017-07-14",
              "tariff":"1339.00",
              "minibreakTariffs":{
                 "threeNight":1071.2,
                 "fourNight":1138.15,
                 "fiveNight":1205.1
              }
           },
           {
              "checkin":"2017-07-21",
              "tariff":"1485.00",
              "minibreakTariffs":{
                 "threeNight":1188,
                 "fourNight":1262.25,
                 "fiveNight":1336.5
              }
           },
           {
              "checkin":"2017-07-28",
              "tariff":"1485.00",
              "minibreakTariffs":{
                 "threeNight":1188,
                 "fourNight":1262.25,
                 "fiveNight":1336.5
              }
           },
           {
              "checkin":"2017-08-04",
              "tariff":"1485.00",
              "minibreakTariffs":{
                 "threeNight":1188,
                 "fourNight":1262.25,
                 "fiveNight":1336.5
              }
           },
           {
              "checkin":"2017-08-11",
              "tariff":"1485.00",
              "minibreakTariffs":{
                 "threeNight":1188,
                 "fourNight":1262.25,
                 "fiveNight":1336.5
              }
           },
           {
              "checkin":"2017-08-18",
              "tariff":"1485.00",
              "minibreakTariffs":{
                 "threeNight":1188,
                 "fourNight":1262.25,
                 "fiveNight":1336.5
              }
           },
           {
              "checkin":"2017-08-25",
              "tariff":"1189.00",
              "minibreakTariffs":{
                 "threeNight":951.2,
                 "fourNight":1010.65,
                 "fiveNight":1070.1
              }
           },
           {
              "checkin":"2017-09-01",
              "tariff":"819.00",
              "minibreakTariffs":{
                 "threeNight":655.2,
                 "fourNight":696.15,
                 "fiveNight":737.1
              }
           },
           {
              "checkin":"2017-09-08",
              "tariff":"819.00",
              "minibreakTariffs":{
                 "threeNight":655.2,
                 "fourNight":696.15,
                 "fiveNight":737.1
              }
           },
           {
              "checkin":"2017-09-15",
              "tariff":"819.00",
              "minibreakTariffs":{
                 "threeNight":655.2,
                 "fourNight":696.15,
                 "fiveNight":737.1
              }
           },
           {
              "checkin":"2017-09-22",
              "tariff":"745.00",
              "minibreakTariffs":{
                 "threeNight":596,
                 "fourNight":633.25,
                 "fiveNight":670.5
              }
           },
           {
              "checkin":"2017-09-29",
              "tariff":"595.00",
              "minibreakTariffs":{
                 "threeNight":476,
                 "fourNight":505.75,
                 "fiveNight":535.5
              }
           },
           {
              "checkin":"2017-10-06",
              "tariff":"595.00",
              "minibreakTariffs":{
                 "threeNight":476,
                 "fourNight":505.75,
                 "fiveNight":535.5
              }
           },
           {
              "checkin":"2017-10-13",
              "tariff":"669.00",
              "minibreakTariffs":{
                 "threeNight":535.2,
                 "fourNight":568.65,
                 "fiveNight":602.1
              }
           },
           {
              "checkin":"2017-10-20",
              "tariff":"745.00",
              "minibreakTariffs":{
                 "threeNight":596,
                 "fourNight":633.25,
                 "fiveNight":670.5
              }
           },
           {
              "checkin":"2017-10-27",
              "tariff":"519.00",
              "minibreakTariffs":{
                 "threeNight":415.2,
                 "fourNight":441.15,
                 "fiveNight":467.1
              }
           },
           {
              "checkin":"2017-11-03",
              "tariff":"519.00",
              "minibreakTariffs":{
                 "threeNight":415.2,
                 "fourNight":441.15,
                 "fiveNight":467.1
              }
           },
           {
              "checkin":"2017-11-10",
              "tariff":"519.00",
              "minibreakTariffs":{
                 "threeNight":415.2,
                 "fourNight":441.15,
                 "fiveNight":467.1
              }
           },
           {
              "checkin":"2017-11-17",
              "tariff":"519.00",
              "minibreakTariffs":{
                 "threeNight":415.2,
                 "fourNight":441.15,
                 "fiveNight":467.1
              }
           },
           {
              "checkin":"2017-11-24",
              "tariff":"519.00",
              "minibreakTariffs":{
                 "threeNight":415.2,
                 "fourNight":441.15,
                 "fiveNight":467.1
              }
           },
           {
              "checkin":"2017-12-01",
              "tariff":"519.00",
              "minibreakTariffs":{
                 "threeNight":415.2,
                 "fourNight":441.15,
                 "fiveNight":467.1
              }
           },
           {
              "checkin":"2017-12-08",
              "tariff":"519.00",
              "minibreakTariffs":{
                 "threeNight":415.2,
                 "fourNight":441.15,
                 "fiveNight":467.1
              }
           },
           {
              "checkin":"2017-12-15",
              "tariff":"519.00",
              "minibreakTariffs":{
                 "threeNight":415.2,
                 "fourNight":441.15,
                 "fiveNight":467.1
              }
           },
           {
              "checkin":"2017-12-22",
              "tariff":"895.00",
              "minibreakTariffs":{
                 "threeNight":716,
                 "fourNight":760.75,
                 "fiveNight":805.5
              }
           },
           {
              "checkin":"2017-12-29",
              "tariff":"1039.00",
              "minibreakTariffs":{
                 "threeNight":831.2,
                 "fourNight":883.15,
                 "fiveNight":935.1
              }
           }
        ]
        
## Retrieve a month of tariffs for a Property [/property/{reference}/tariff/{year}/{month}]

Returns the calendar for the requested month with standard and minibreak tariff for each day of the
month where there is availability. If a discount is available this has already been applied to the tariff(s).

+ Parameters
    + reference (string) - reference ID of the property resource in the form of a string
    + year (number) - full numeric representation of a year (4 digits) in the form of an integer
    + month (number) - numeric representation of the month without leading zeros in the form of an integer 

### Tariff [GET]

+ Response 200 (application/json)

        [
           "2017-05-01":{
              "status":"B"
           },
           "2017-05-02":{
              "status":"B"
           },
           "2017-05-03":{
              "status":"B"
           },
           "2017-05-04":{
              "status":"B"
           },
           "2017-05-05":{
              "status":"U"
           },
           "2017-05-06":{
              "status":"U"
           },
           "2017-05-07":{
              "status":"U"
           },
           "2017-05-08":{
              "status":"U"
           },
           "2017-05-09":{
              "status":"U"
           },
           "2017-05-10":{
              "status":"U"
           },
           "2017-05-11":{
              "status":"U"
           },
           "2017-05-12":{
              "status":"B"
           },
           "2017-05-13":{
              "status":"B"
           },
           "2017-05-14":{
              "status":"B"
           },
           "2017-05-15":{
              "status":"B"
           },
           "2017-05-16":{
              "status":"B"
           },
           "2017-05-17":{
              "status":"B"
           },
           "2017-05-18":{
              "status":"B"
           },
           "2017-05-19":{
              "status":"B"
           },
           "2017-05-20":{
              "status":"B"
           },
           "2017-05-21":{
              "status":"B"
           },
           "2017-05-22":{
              "status":"B"
           },
           "2017-05-23":{
              "status":"B"
           },
           "2017-05-24":{
              "status":"B"
           },
           "2017-05-25":{
              "status":"B"
           },
           "2017-05-26":{
              "status":"A",
              "weeklyTariff":"951.20",
              "minibreaks":{
                 "threeNights":760.96,
                 "fourNights":808.52,
                 "fiveNights":856.08
              },
              "discount":{
                 "originalTariff":"1189.00",
                 "discountCode":"X20250517X",
                 "discountName":"20% Discount for week commencing 25th May 2017",
                 "discountRate":"20%"
              }
           },
           "2017-05-27":{
              "status":"A",
              "weeklyTariff":"951.20",
              "discount":{
                 "originalTariff":"1189.00",
                 "discountCode":"X20250517X",
                 "discountName":"20% Discount for week commencing 25th May 2017",
                 "discountRate":"20%"
              }           
           },
           "2017-05-28":{
                "status":"U"
           },
           "2017-05-29":{
              "status":"A",
              "weeklyTariff":"951.20",
              "minibreaks":{
                 "threeNights":760.96,
                 "fourNights":808.52
              },
              "discount":{
                 "originalTariff":"1189.00",
                 "discountCode":"X20250517X",
                 "discountName":"20% Discount for week commencing 25th May 2017",
                 "discountRate":"20%"
              }
           },
           "2017-05-30":{
              "status":"A",
              "weeklyTariff":"951.20",
              "minibreaks":{
                 "threeNights":760.96
              },
              "discount":{
                 "originalTariff":"1189.00",
                 "discountCode":"X20250517X",
                 "discountName":"20% Discount for week commencing 25th May 2017",
                 "discountRate":"20%"
              }
           },
           "2017-05-31":{
              "status":"A",
              "weeklyTariff":"951.20",
              "discount":{
                 "originalTariff":"1189.00",
                 "discountCode":"X20250517X",
                 "discountName":"20% Discount for week commencing 25th May 2017",
                 "discountRate":"20%"
              }
           }
        ]


# Group Last minute offers

## Last minute offers [/offer/lastminute]

### Get a list of offers [GET]

+ Response 200

        [
            {
                "type": "%",
                "amount": 15
                "daysToHolidayMin": 0,
                "daysToHolidayMax": 7,
                "description": "15% off bookings made within 7 days of the start date",
                "properties": [
                    "mousecott_SS"
                ]
            },
            {
                "type": "%",
                "amount": 10
                "daysToHolidayMin": 7,
                "daysToHolidayMax": 14,
                "description": "10% off bookings made between 8 and 14 days before the start date",
                "properties": [
                    "mousecott_SS"
                ]
            },
        ]


# Group Booking resources

## Create a provisional booking [/booking]

This is for consideration. Only guest data is stored within the PMS. Need to decide how to handle 
remarketing of abandoned bookings for non guests.

### Create a new booking [POST]

+ Request (application/json)

        {
            "propertyId": 10006,
            "checkin": "2017-08-01",
            "checkout": "2017-08-08",
            "adults": 2,
            "children": 1,
            "infants": 0,
            "pets": 2
        }

+ Response 201 (application/json)


        {
            "bookingReference": 12341234,
            "propertyId": 10006,
            "guestId": null,
            "added": "2017-05-26",
            "checkin": "2017-08-01",
            "checkout": "2017-08-08",
            "checkinTime": "4:30pm",
            "status": "P",
            "type": "W",
            "contactInformation": {
                "primary": null,
                "secondary": null,
            },
            "partyDetails": {
                "adults": 2,
                "children": 1,
                "infants": 0,
                "dogs": 2
            },
            "tariff": {
                "total": 999.00,
                "deposit": 333.00,
                "balance": 666.00,
                "extras": 29.00
            }
            "extras": [
                {
                    "extraId": "Pet01",
                    "description": "Pet Supplement (Cornish Gem)",
                    "comments": "1 x Pet Supplement (Cornish Gem)",
                    "net": 24.17,
                    "vat": 4.83,
                    "gross": 29.00
                }
            ],
            "receipts": [ ],
            "balanceDue": "2017-07-01"
        }

## Get a booking [/booking/{bookingReference}]

+ Parameters
    + bookingReference (int) - reference ID of the booking as an integer

### Get details of a booking [GET]

+ Response 200 (application/json)

        {
            "bookingReference": 12341234,
            "propertyId": 10006,
            "guestId": null,
            "added": "2017-05-26",
            "checkin": "2017-08-01",
            "checkout": "2017-08-08",
            "checkinTime": "4:30pm",
            "status": "P",
            "type": "W",
            "contactInformation": {
                "primary": null,
                "secondary": null,
            },
            "partyDetails": {
                "adults": 2,
                "children": 1,
                "infants": 0,
                "dogs": 2
            },
            "tariff": {
                "total": 999.00,
                "deposit": 333.00,
                "balance": 666.00,
                "extras": 29.00
            }
            "extras": [
                {
                    "extraId": "Pet01",
                    "description": "Pet Supplement (Cornish Gem)",
                    "comments": "1 x Pet Supplement (Cornish Gem)",
                    "net": 24.17,
                    "vat": 4.83,
                    "gross": 29.00
                }
            ],
            "receipts": [ ],
            "balanceDue": "2017-07-01"
        }

## Add guest to a booking [/booking/{bookingReference}/guest]

### Add guest reference [PUT]

+ Request (application/json)

        {
            "guestId": 9021,
            "contactInformation": {
                "primary": "07878172172",
                "secondary": "01234512313,
            }
        }

+ Response 204


            
# Group Guest resources

## Guest [/guest/{guest_id}]

+ Parameters
    + guest_id (integer) - guest ID in the form of an integer

### Get an individual customer [GET]

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }           
            
### Update a guest's details [PUT]   

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }
            
## Guest bookings [/guest/{guest_id}/bookings]

+ Parameters
    + guest_id (integer) - guest ID in the form of an integer

### Get a list of bookings associated with a Guest [GET]

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }     
            
# Group Owner resources

## Owner [/owner/JBLOG]

### Get an owner [GET]

+ Response 200

        {
            "reference" : "JBLOG",
            "brandCode" : "SS",
            "accountingBrandCode" : "SS",
            "name": {
                "title": "Mr",
                "firstName": "J",
                "surname": "Bloggs",
                "salutation": "Joe"
            },
            "address": {
                "addr1": "Carlton House",
                "addr2": "Market Place",
                "town": "Reepham",
                "county": "Norfolk",
                "postcode": "NR10 4JJ",
                "country": "GB"
            },
            "daytimePhone": "01603 871872",
            "eveningPhone": "01603 872871",
            "mobilePhone": "07999 123456",
            "email": "support@carltonsoftware.co.uk",
            "fax": "01603 871872",
            "bankAccountDetails": {
                "bankAccountName": "MR J BLOGGS",
                "bankAccountNumber": "87560824",
                "bankAccountSortCode": "12-34-56",
                "bankName": "HSBC",
                "bankAddress": {
                    "addr1": "HSBC",
                    "addr2": "Market Place",
                    "town": "Reepham",
                    "county": "Norfolk",
                    "postcode": "NR10 4JJ",
                    "country": "GB"
                },
                "bankReference": "",
                "bankPaymentReference": "",
                "vatNumber": "",
                "vatRegistered": false
            },
            "postConfirmations": true,
            "emailConfirmations": true,
            "properties": [
                {
                    "reference": "mousecott",
                    "brandCode": "SS"
                }
            ]
        }


### Update an owner [PUT]

+ Request (application/json)

        {
            "reference" : "JBLOG",
            "brandCode" : "SS",
            "accountingBrandCode" : "SS",
            "name": {
                "title": "Mr",
                "firstName": "J",
                "surname": "Bloggs",
                "salutation": "Joe"
            },
            "address": {
                "addr1": "Carlton House",
                "addr2": "Market Place",
                "town": "Reepham",
                "county": "Norfolk",
                "postcode": "NR10 4JJ",
                "country": "GB"
            },
            "daytimePhone": "01603 871872",
            "eveningPhone": "01603 872871",
            "mobilePhone": "07999 123456",
            "email": "support@carltonsoftware.co.uk",
            "fax": "01603 871872",
            "bankAccountDetails": {
                "bankAccountName": "MR J BLOGGS",
                "bankAccountNumber": "87560824",
                "bankAccountSortCode": "12-34-56",
                "bankName": "HSBC",
                "bankAddress": {
                    "addr1": "HSBC",
                    "addr2": "Market Place",
                    "town": "Reepham",
                    "county": "Norfolk",
                    "postcode": "NR10 4JJ",
                    "country": "GB"
                },
                "bankReference": "",
                "bankPaymentReference": "",
                "vatNumber": "",
                "vatRegistered": false
            },
            "postConfirmations": true,
            "emailConfirmations": true,
            "properties": [
                {
                    "reference": "mousecott",
                    "brandCode": "SS"
                }
            ]
        }

+ Response 204


## Authenticate an owner [/owner/JBLOG/password/authenticate]

### Authenticate an owner [PUT]

+ Request (application/json)

        {
            "password": "apassword"
        }

+ Response 204


## Set an owners password [/owner/JBLOG/password]

### Set an owner password [PUT]

+ Request (application/json)

        {
            "password": "apassword"
        }

+ Response 204


## Owner documents [/owner/JBLOG/document]

### Get a list of owner documents [GET]

+ Response 200

        [
            {
                "id": 1,
                "filename": "statement.pdf",
                "mimetype": "application/pdf",
                "type": "statement"
            }
        ]


## Owner document [/owner/JBLOG/document/1]

### Get a specific owner document [GET]

+ Response 200

        {
            "id": 1,
            "filename": "statement.pdf",
            "mimetype": "application/pdf",
            "type": "statement"
        }


## Owner document [/owner/JBLOG/document/1/data]

### Retrieve the document data [GET]

+ Response 200